"""Shared task-module constants: status labels, API error codes, timezone."""

from zoneinfo import ZoneInfo

TASK_STATUS_LABELS = {
    "pending": "待发布",
    "in_progress": "进行中",
    "completed": "已完成",
    "cancelled": "已取消",
    "archived": "已归档",
}

TASK_ERROR_PARAM = 62001
TASK_ERROR_EMPTY_DATES = 62002
TASK_ERROR_INVALID_DATES = 62003
TASK_ERROR_UNSUPPORTED_TYPE = 62004
TASK_ERROR_DUPLICATE_DATE = 62006
TASK_ERROR_NOT_EXECUTION_DAY = 62007
TASK_ERROR_EXECUTION_COMPLETED = 62008
TASK_ERROR_EXECUTION_NOT_FOUND = 62009
TASK_ERROR_NOT_FOUND = 62010
TASK_ERROR_PHOTO_INVALID = 62011
TASK_ERROR_MAP_POINT_INVALID = 62012
TASK_ERROR_STATUS_CONFLICT = 62013
TASK_ERROR_CANCELLED_CANNOT_CHECKIN = 62015

LOCAL_TZ = ZoneInfo("Asia/Shanghai")
EXECUTION_REMOVED_CANCEL_REASON = "管理员调整执行日期，该子任务自动取消"
